<?php

/**
 * Implementation of hook_user().
 */
function osso_provider_user($op, &$edit, &$account) {
  switch ($op) {
    case 'insert':
    case 'update':
      // Set an alias for this user.
      path_set_alias('user/'. $account->uid, 'user/'. $account->name);
      break;
    case 'delete':
      path_set_alias('user/'. $account->uid);
      break;
  }
}

/**
 * Implementation of hook_strongarm().
 */
function osso_provider_strongarm() {
  return array (
    'user_email_verification' => 0,
  );
}

/**
 * Implementation hook_menu_alter().
 */
function osso_provider_menu_alter(&$items) {
  foreach (array('user', 'logout') as $path) {
    $items[$path]['menu_name'] = 'primary-links';
    $items[$path]['type'] = MENU_NORMAL_ITEM;
  }
  $items['user']['title callback'] = 'osso_provider_user_menu_title';
  $items['user/register']['title callback'] = 'osso_provider_register_menu_title';
}

/**
 * Implementation of hook_form_alter()
 */
function osso_provider_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_register' || $form_id == 'user_login' || $form_id == 'user_pass') {
    $links = array(
      l(t('Log in'), 'user/login'),
      l(t('Sign up'), 'user/register'),
      l(t('Forgot password?'), 'user/password')
    );
    $form['links']['#value'] = theme('item_list', $links, NULL, 'ul', array('class' => 'links osso-tabs'));
    $form['links']['#weight'] = -10;
  }
}

/**
 * Custom title callback.
 */
function osso_provider_user_menu_title() {
  global $user;
  if ($user->uid) {
    return t('Hello @user', array('@user' => $user->name));
  }
  return t('Log in / Sign up');
}

/**
 * Custom title callback.
 */
function osso_provider_register_menu_title() {
  return t('Sign up');
}
