<?php

/**
 * @file
 * Hook implementations and callbacks for OpenID Provider Trusted Web.
 */

/**
 * Implementation of hook_user().
 *
 * Add trusted Relying Parties to a new user on creation.
 */
function openid_provider_trusted_user($op, &$edit, &$account) {
  if ($op == 'insert') {
    module_load_include('inc', 'openid_provider');
    foreach (variable_get('openid_provider_trusted_rps', array()) as $realm) {
      _openid_provider_rp_save($account->uid, $realm, TRUE);
    }
  }
}